version: "3.8"

x-environment: &environment
  SERVER_HOST: 0.0.0.0
  REDIS_HOST: db.redis

services:
  db.redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379

  service.control-tower:
    build: ./services/control-tower
    image: lab-automation-playground/service.control-tower:latest
    env_file:
      - ./services/control-tower/.env
    environment:
      <<: *environment

  service.ot-builder:
    build: ./services/ot-builder
    image: lab-automation-playground/service.ot-builder:latest
    ports:
      - 8000:8000
    environment:
      <<: *environment
